name: ME570X_cpu_mac
channels:
  - anaconda
  - conda-forge/label/cf201901  
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - pip
  - vtk
  - mayavi
  - trimesh
  - pip:
    - scikit-image
    - pyglet


